/* -------------------------------------------------------------------
* .java
* versión 1.0
* Copyright (C) 2016  Kan-Balam.
* Facultad de Ciencias,
* Universidad Nacional Autónoma de México, Mexico.
*
* Este programa es software libre; se puede redistribuir
* y/o modificar en los términos establecidos por la
* Licencia Pública General de GNU tal como fue publicada
* por la Free Software Foundation en la versión 2 o
* superior.
*
* Este programa es distribuido con la esperanza de que
* resulte de utilidad, pero SIN GARANTÍA ALGUNA; de hecho
* sin la garantía implícita de COMERCIALIZACIÓN o
* ADECUACIÓN PARA PROPÓSITOS PARTICULARES. Véase la
* Licencia Pública General de GNU para mayores detalles.
*
* Con este programa se debe haber recibido una copia de la
* Licencia Pública General de GNU, de no ser así, visite el
* siguiente URL:
* http://www.gnu.org/licenses/gpl.html
* o escriba a la Free Software Foundation Inc.,
* 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
* -------------------------------------------------------------------
*/
package modelo;
// Generated 08-abr-2016 1:26:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agente generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private int idAgente;
     private Usuario usuario;
     private String ocupacion;
     private Double reputacionAgente;
     private Set servicios = new HashSet(0);

    public Agente() {
    }

	
    public Agente(Usuario usuario) {
        this.usuario = usuario;
    }
    public Agente(Usuario usuario, String ocupacion, Double reputacionAgente, Set servicios) {
       this.usuario = usuario;
       this.ocupacion = ocupacion;
       this.reputacionAgente = reputacionAgente;
       this.servicios = servicios;
    }
   
    public int getIdAgente() {
        return this.idAgente;
    }
    
    public void setIdAgente(int idAgente) {
        this.idAgente = idAgente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Double getReputacionAgente() {
        return this.reputacionAgente;
    }
    
    public void setReputacionAgente(Double reputacionAgente) {
        this.reputacionAgente = reputacionAgente;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }

    public boolean tieneOcupacion(){
        return !(this.ocupacion == null || this.ocupacion.trim().equals(""));
    }


}


