package modelo;
// Generated 08-abr-2016 1:26:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especialidad generated by hbm2java
 */
public class Especialidad  implements java.io.Serializable {


     private int idEspecialidad;
     private String especialidad;
     private Set programadors = new HashSet(0);

    public Especialidad() {
    }

	
    public Especialidad(int idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public Especialidad(int idEspecialidad, String especialidad, Set programadors) {
       this.idEspecialidad = idEspecialidad;
       this.especialidad = especialidad;
       this.programadors = programadors;
    }
   
    public int getIdEspecialidad() {
        return this.idEspecialidad;
    }
    
    public void setIdEspecialidad(int idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Set getProgramadors() {
        return this.programadors;
    }
    
    public void setProgramadors(Set programadors) {
        this.programadors = programadors;
    }




}


