package modelo;
// Generated 08-abr-2016 1:26:04 by Hibernate Tools 4.3.1



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private int idMensaje;
     private String mensaje;
     private Registro registro;

    public Mensaje() {
    }

	
    public Mensaje(int idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Mensaje(int idMensaje, String mensaje, Registro registro) {
       this.idMensaje = idMensaje;
       this.mensaje = mensaje;
       this.registro = registro;
    }
   
    public int getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(int idMensaje) {
        this.idMensaje = idMensaje;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }




}


