package modelo;
// Generated May 6, 2016 1:12:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mensaje generated by hbm2java
 */
@Entity
@Table(name = "mensaje", schema = "public"
)
public class Mensaje implements java.io.Serializable {

    private int idMensaje;
    private Servicio servicio;
    private Usuario usuarioByIdRemitente;
    private Usuario usuarioByIdDestinatario;
    private String texto;
    private Date fechaDeEnvio;

    public Mensaje() {
    }

    public Mensaje(int idMensaje, Date fechaDeEnvio) {
        this.idMensaje = idMensaje;
        this.fechaDeEnvio = fechaDeEnvio;
    }

    public Mensaje(int idMensaje, Servicio servicio,
            Usuario usuarioByIdRemitente, Usuario usuarioByIdDestinatario,
            String texto, Date fechaDeEnvio) {
        this.idMensaje = idMensaje;
        this.servicio = servicio;
        this.usuarioByIdRemitente = usuarioByIdRemitente;
        this.usuarioByIdDestinatario = usuarioByIdDestinatario;
        this.texto = texto;
        this.fechaDeEnvio = fechaDeEnvio;
    }

    @Id

    @Column(name = "id_mensaje", unique = true, nullable = false)
    public int getIdMensaje() {
        return this.idMensaje;
    }

    public void setIdMensaje(int idMensaje) {
        this.idMensaje = idMensaje;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_servicio")
    public Servicio getServicio() {
        return this.servicio;
    }

    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_remitente")
    public Usuario getUsuarioByIdRemitente() {
        return this.usuarioByIdRemitente;
    }

    public void setUsuarioByIdRemitente(Usuario usuarioByIdRemitente) {
        this.usuarioByIdRemitente = usuarioByIdRemitente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_destinatario")
    public Usuario getUsuarioByIdDestinatario() {
        return this.usuarioByIdDestinatario;
    }

    public void setUsuarioByIdDestinatario(Usuario usuarioByIdDestinatario) {
        this.usuarioByIdDestinatario = usuarioByIdDestinatario;
    }

    @Column(name = "texto")
    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_de_envio", nullable = false, length = 29)
    public Date getFechaDeEnvio() {
        return this.fechaDeEnvio;
    }

    public void setFechaDeEnvio(Date fechaDeEnvio) {
        this.fechaDeEnvio = fechaDeEnvio;
    }

}
