/** DATOS DE USUARIOS GENERALES */


INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Hedy','Pollard','Valentine',5476471428,'massa@leoinlobortis.co.uk','JIV32KCP5YN','Jhelum','2017-02-13','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Akeem','Daniels','Singleton',1404441359,'non@Cras.edu','TUB68PHA8RE','Mostazal','2015-06-02','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Shafira','Griffin','Mcpherson',4267530181,'vel.est.tempor@pharetraQuisqueac.edu','DFK69AJX9FW','Calgary','2015-06-21','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Belle','Barry','Hobbs',8393497836,'accumsan.laoreet.ipsum@a.net','YVX87XTC5LF','Salles','2016-07-09','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Herrod','Oconnor','Cain',1837676534,'id.nunc@augue.co.uk','QNU38VOO9XZ','Rotheux-RimiŽre','2017-01-26','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Mariko','Sosa','Sears',1694597751,'non@semperegestas.ca','LQC04YGW0CE','Wimbledon','2015-06-25','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Neil','Combs','Leach',1660589310,'sollicitudin@hendrerit.org','JNG08KBI6DF','Tongerlo','2016-02-09','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Reed','Stone','Holden',1554622510,'Duis.at.lacus@sedliberoProin.co.uk','KQY31YKU8PO','Cercepiccola','2015-05-29','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Cora','Terry','Benson',2362674469,'Cum.sociis@quamquis.edu','CNV45RKT8KY','Zelem','2016-01-22','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Rosalyn','English','Cardenas',7980069815,'tellus@pellentesquea.com','LOX07KPK2OP','Asnières-sur-Seine','2016-06-20','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Isabella','Delacruz','Kelley',6968574844,'lorem@etmalesuadafames.edu','AVK27GRC9LR','Bersillies-l''Abbaye','2016-11-30','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Barclay','Warner','Parsons',2433747285,'orci.luctus.et@sit.edu','PYJ24NHF9GD','Emarèse','2015-11-19','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Cathleen','Pollard','Klein',5043636082,'sodales.elit@Pellentesque.org','LLB03YCH6WS','Avernas-le-Bauduin','2015-09-13','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Stuart','Brooks','Lamb',8469898711,'Etiam.bibendum.fermentum@liberoatauctor.com','GSR27VJR3CI','Rutten','2016-09-25','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Jorden','Harper','Lowe',5666439074,'porttitor.eros@eget.com','CPX41QMO6RK','Bayonne','2016-05-13','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Bryar','Farley','Irwin',6278427118,'eleifend.vitae.erat@faucibus.com','UYE39HCK9UN','Rueil-Malmaison','2016-05-29','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Zenia','Bradley','Mckenzie',7347497780,'elit.sed.consequat@feugiat.net','BWA04TET9SN','Créteil','2017-03-11','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Zenaida','Butler','Cantu',9713142051,'sit.amet.faucibus@augueut.co.uk','LJU99KAZ0HV','Bihain','2016-02-19','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Susan','Lott','Becker',1592985685,'dis.parturient.montes@vel.org','RHN81GIJ8FO','Huissen','2015-06-08','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Naida','Goodman','Dixon',7772278777,'scelerisque@Sedpharetra.com','JAA94MCW6AJ','Villa Santo Stefano','2016-10-24','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kellie','Olson','Gilbert',9649138767,'est.mollis@dolorDonec.co.uk','IWB29JPD9YE','Quickborn','2015-11-01','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Reed','Wiley','Fowler',7712345193,'Cras@consequat.net','JAG63RJJ3ST','Moncton','2016-07-13','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Daria','Reyes','Hancock',6023262275,'erat@maurisaliquam.net','HAC34JQT4IQ','Des Moines','2016-12-26','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Paul','Anderson','Boone',8727782182,'pede.blandit.congue@libero.org','LRZ67DIU5AL','Wakefield','2015-05-22','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Russell','Bell','Strickland',4969378299,'sed.tortor.Integer@egetvarius.edu','MIR06JMG1DR','Balıkesir','2016-11-13','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Ivory','Baxter','Maxwell',7307079993,'penatibus.et@atarcu.edu','PYO14MYK7RX','Frutillar','2015-07-22','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Stephanie','Golden','Boyd',4584143436,'Nulla.interdum.Curabitur@risusDuis.org','IAA13ECN0UZ','Destelbergen','2017-01-19','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Zephania','Clay','Frank',3999595918,'euismod@maurisblandit.co.uk','ZZC77UVP0BD','Palmerston','2016-09-10','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Lawrence','Ramirez','Lewis',3543009238,'dis@Sed.edu','ALQ42NWO9VZ','Kilmarnock','2015-04-17','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Isadora','Dickson','Garcia',1791608876,'cursus.luctus@eleifendvitaeerat.org','APA37NTP9SG','Pugwash','2016-10-31','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Martina','Tyson','Vazquez',4569154005,'Praesent@eutemporerat.com','HTT78YIN3PN','Quickborn','2015-07-29','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Ali','Rich','Wilson',2582522548,'risus.Donec@amet.com','QTL65QJT4NJ','Castelbuono','2015-07-04','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Ignatius','Campbell','Shelton',1959612072,'Integer.vulputate@Curabitur.com','MFV99ANY5EE','Castel Volturno','2017-03-09','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Paula','Cooper','Henson',7115004321,'felis.orci.adipiscing@variusultricesmauris.org','VXR55TYU1HV','Armungia','2015-05-12','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Bradley','Parsons','Combs',5608746451,'purus.sapien.gravida@eratsemper.co.uk','XPM63RZS9QZ','New Glasgow','2017-03-18','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Chelsea','Black','Savage',2496739948,'pharetra.sed.hendrerit@sagittis.com','ARL38SDL5BV','Millport','2016-10-20','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Cassidy','Reilly','Pugh',2780874852,'molestie.orci@egestasAliquam.org','PPE32GIP7JX','Raymond','2015-11-12','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kasimir','Stafford','Beck',7168676039,'pede@egestas.com','DIR96SFZ3NT','Bedollo','2016-01-24','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Cameron','Anderson','Sandoval',4444341991,'tortor@ornareelitelit.co.uk','TTG03SEW8PF','Cowdenbeath','2016-07-11','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Molly','Huff','Mckay',7846074464,'Nam.porttitor.scelerisque@sagittisplaceratCras.ca','QUG99YGU2EV','Sint-Ulriks-Kapelle','2016-05-15','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Dana','Ruiz','Vaughn',3602156429,'Proin.ultrices.Duis@enimcondimentum.edu','CQS04CCV0QO','Wilmington','2017-01-03','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Gillian','Huber','Colon',2443251894,'netus.et@Etiam.ca','RYE59NCS7SK','Polino','2016-07-23','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Adam','Clayton','Rivas',6753332560,'mauris.a.nunc@ut.com','GMI23ZSQ7UE','Pichidegua','2016-06-19','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Carlos','Richards','Leon',8935814890,'molestie@Vivamusnibh.net','BWN08CRF2AE','Taupo','2015-10-27','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Tasha','Dudley','Hendricks',8482255975,'tempor.erat.neque@arcu.org','UWY83PMD2DU','Richmond Hill','2017-03-06','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Josephine','Levy','Harrison',8130282852,'Lorem.ipsum.dolor@sed.ca','YZF83GSC4UI','Tuktoyaktuk','2017-04-04','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('George','Serrano','Edwards',6480238731,'amet.luctus@vitae.edu','ERC29YYN4BP','Gap','2016-09-26','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Elmo','Russo','Camacho',8335169504,'Cras.vehicula.aliquet@sem.co.uk','IBV16MHF2AJ','North Saanich','2016-04-28','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Echo','Deleon','Mathis',8855145880,'suscipit@Uttincidunt.edu','AYF91PBW0TT','Herstal','2016-02-21','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Summer','Burris','Wall',7523777778,'iaculis.odio.Nam@tellus.edu','KNF05BBT7LA','Dieppe','2017-01-04','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Vincent','Jarvis','Mcclain',5330245237,'posuere@auctorvelit.com','KLH22UVG8NO','Jaboatão dos Guararapes','2015-12-17','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Inez','Navarro','Gilbert',2312268981,'urna.Vivamus.molestie@congue.net','TDM65OSK9RW','Fernie','2015-05-29','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Aretha','Morton','Dalton',8606893242,'lectus.rutrum.urna@ornarefacilisiseget.com','RNF33WFW8KK','Orilla','2017-01-14','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Imogene','Meyer','Dorsey',7205625795,'Mauris.vestibulum@variusultrices.edu','VES35YVC4PR','Caplan','2015-12-11','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Mohammad','Casey','Lyons',3544836793,'neque@nullavulputate.net','YTY51RTR5LA','Sacramento','2016-07-22','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Sloane','Mack','Daugherty',9438568067,'nisl.sem@cursuset.ca','ZNL67CHG0DY','Haarlem','2015-06-02','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Blythe','Weber','Mooney',3237995483,'pharetra@quis.org','UYZ03SBJ8MZ','Cochrane','2015-09-08','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kenneth','Pope','Blake',6755198764,'sapien.Cras@auctor.ca','YND47CWA7PJ','Tillicoultry','2016-06-22','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Justine','Leonard','Adkins',1387965871,'enim.Etiam.imperdiet@aneque.edu','SFX23YZX8PZ','Columbus','2017-03-04','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Tanya','Hooper','Johnston',8189360074,'Donec.elementum.lorem@lectus.co.uk','CBH00EUI3KU','Lampernisse','2016-03-02','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Dahlia','Donaldson','Levine',2403644113,'tincidunt.nunc@sed.org','JQA42LPC0IK','Kohima','2016-10-31','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Gary','Sykes','Morgan',8377527729,'nec.quam@convallis.co.uk','HPS88BCT9IW','Castel Ritaldi','2016-04-25','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Chastity','Bauer','Cameron',5574963087,'suscipit.nonummy.Fusce@consequatnec.net','JRD29ITH8SG','Maranello','2017-04-07','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Lester','Pickett','Estrada',1345293279,'cursus@tacitisociosqu.co.uk','YTO95SET2UB','Soverzene','2015-06-18','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Ross','Battle','Blair',5253976177,'neque@etlibero.net','OEO18UKW3WE','Camaragibe','2016-12-04','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Avye','Rose','Flowers',9420026941,'diam.Pellentesque@Suspendissedui.org','JAU62ICE2EN','Valparaíso de Goiás','2016-08-20','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kristen','Leonard','Miranda',4387264042,'natoque@euodio.ca','JHT49YZQ0HU','Hertsberge','2016-12-13','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Shana','Estes','Barber',8713276018,'nec.metus@inmagnaPhasellus.ca','YTX98OJT5RE','Profondeville','2015-05-20','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Shaeleigh','Lowery','Cline',6181282582,'Proin.velit@enimnon.org','GXK54HEP3WQ','Quemchi','2015-06-09','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Lucius','Baker','Williamson',4514958576,'imperdiet.nec.leo@Integer.net','EUS51BKA7TG','Birmingham','2015-08-15','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kato','Mcfarland','Houston',1590475156,'penatibus.et@ataugueid.com','WWT85QVZ1TI','Hervey Bay','2016-05-23','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Orli','Kemp','Fleming',8549765055,'Nunc@perinceptos.co.uk','DWQ22HHD7JE','Bhagalpur','2016-12-31','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Amal','Foster','Savage',5010618985,'lorem.ipsum.sodales@ornare.co.uk','WBF34BEG8ON','Rouyn-Noranda','2016-02-04','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Halla','Aguilar','Dillard',4373224497,'Donec@utsemNulla.ca','WGD74REY7EQ','Castel Guelfo di Bologna','2015-04-15','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Gage','Brown','Townsend',8537928832,'semper.rutrum.Fusce@Nam.net','NWV81WRC7RT','Bard','2015-09-08','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Clare','Dorsey','Wilson',7008839178,'elit@urnaNunc.com','CET84PFZ3XB','Columbus','2016-12-20','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Talon','Moses','Ross',6577463803,'In.ornare@Maurisquis.net','RJA65IZJ6WE','Couture-Saint-Germain','2017-01-18','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Abigail','Mendoza','Ferrell',4894137012,'magna@arcu.org','FMO21ENZ0SH','Huasco','2016-09-05','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Savannah','Duncan','Carter',3013060835,'a.facilisis.non@amagnaLorem.net','KUG80ZUW6MY','Badajoz','2016-10-22','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Baker','Hartman','Huffman',2384328211,'Nunc@Sednuncest.co.uk','HMC44UGJ8TZ','Buxton','2016-05-11','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Aaron','Klein','Kemp',3007864088,'pharetra@Sed.co.uk','CLI86XMY4RI','Taupo','2015-06-28','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Galena','Sloan','Skinner',2431043760,'egestas.Aliquam.nec@Phasellusornare.org','NDN57SLM4DC','Comox','2015-06-14','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Porter','Graham','Vaughn',7952447216,'ac.mattis@magnisdisparturient.com','XSD54BHR3HH','New Galloway','2016-06-11','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Christian','Clark','Sargent',9260162896,'habitant.morbi@enimCurabiturmassa.net','QLP34KRD2QD','San Damiano al Colle','2017-03-16','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Nathan','Kramer','Hernandez',7762406155,'mollis.lectus@idante.org','YLR42KDI9EV','Auldearn','2017-01-10','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Jasmine','Brooks','Sparks',3926603322,'Pellentesque.habitant@velmauris.net','IRA44KTY1QQ','Vieux-Genappe','2016-06-01','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Lysandra','Maldonado','Woodward',5948733110,'lectus@disparturientmontes.ca','IIP25ADD8NT','Mont-Saint-Guibert','2017-01-09','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Brendan','Faulkner','Powers',4645477650,'faucibus.orci.luctus@Phasellusataugue.org','KAE30LZT0DV','Toulon','2016-03-26','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Jesse','Sellers','Huff',7286730909,'orci.quis@mienim.com','UWD60FIB0NY','Tamworth','2017-01-23','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Kameko','Richards','Dillon',9324273289,'Aenean@Aeneanegestashendrerit.net','AFZ28DQA0TF','Vastogirardi','2016-12-14','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Aphrodite','Bullock','Head',2085911180,'enim@Praesentinterdumligula.net','GOB98LUL6OV','St. Albert','2016-06-08','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Rinah','Valencia','Macdonald',3770582107,'a@dignissim.co.uk','CTK85MZP5MU','Bellevue','2017-01-31','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Ori','Montgomery','Bartlett',7972449064,'Donec.nibh.Quisque@condimentumDonec.ca','HAF30UHU1IJ','Temuco','2015-08-27','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Aurelia','Browning','Adams',3339009998,'fermentum@Donecsollicitudin.com','YYX61KOK9TD','Sfruz','2015-08-03','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Karyn','Morales','Hernandez',2269375275,'purus.mauris@quis.org','GVS20CHU5RW','Mobile','2015-10-13','M');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Garrett','Talley','Gould',7879889008,'sapien@insodales.net','HXP62RLJ3LS','Guelph','2017-02-02','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Maggie','Hodge','Harper',4122308208,'mi.felis@dictumsapien.org','UKW74MTK3FX','Beaumaris','2016-10-13','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Bo','Bauer','Mclean',4809225949,'interdum.Nunc@Innecorci.edu','OWZ17LQW1AR','Port Coquitlam','2017-03-30','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Maris','Mathews','Casey',7733806727,'ipsum.ac@nec.org','ECJ66YLD5ZB','Asnières-sur-Seine','2016-07-06','H');
INSERT INTO "usuario" (nombre,apellido_paterno,apellido_materno,telefono,correo,contrasenia,estado,fecha_de_naciminiento,genero) VALUES ('Nicole','Howard','Haynes',1793287529,'sed.libero@eu.com','HFO41ZMZ8EP','Łódź','2016-05-08','H');

/** DATOS DE PROGRAMADORES (50 PRIMEROS) */

INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',29);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',97);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',31);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet,',85);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',48);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer',82);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',30);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',92);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',24);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem',11);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur',70);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',85);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',95);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet,',6);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing',77);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',60);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',55);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum',60);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur',82);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',29);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum',19);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',16);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum',40);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur',68);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',33);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet,',71);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing',31);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing',97);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum',92);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem',36);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem',20);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',39);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem',64);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',82);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing',4);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing',24);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer',78);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',92);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur',48);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',25);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer',67);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',10);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed',18);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',13);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',59);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',27);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',56);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor',85);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit',58);
INSERT INTO "programador" (formacion,reputacion_programador) VALUES ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',74);

/** DATOS DEL AGENTE CREATIVO */

INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (51,'Customer Service',83);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (52,'Human Resources',30);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (53,'Quality Assurance',43);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (54,'Accounting',72);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (55,'Finances',22);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (56,'Accounting',56);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (57,'Advertising',50);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (58,'Customer Service',37);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (59,'Quality Assurance',87);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (60,'Advertising',94);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (61,'Customer Relations',94);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (62,'Human Resources',55);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (63,'Quality Assurance',76);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (64,'Customer Relations',4);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (65,'Customer Service',99);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (66,'Sales and Marketing',73);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (67,'Public Relations',94);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (68,'Customer Service',67);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (69,'Asset Management',38);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (70,'Tech Support',10);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (71,'Tech Support',44);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (72,'Tech Support',88);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (73,'Finances',75);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (74,'Human Resources',30);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (75,'Sales and Marketing',23);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (76,'Customer Service',25);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (77,'Customer Relations',20);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (78,'Legal Department',93);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (79,'Research and Development',14);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (80,'Sales and Marketing',67);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (81,'Quality Assurance',65);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (82,'Human Resources',9);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (83,'Payroll',80);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (84,'Media Relations',22);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (85,'Customer Service',11);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (86,'Customer Service',44);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (87,'Legal Department',50);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (88,'Legal Department',93);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (89,'Tech Support',99);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (90,'Finances',61);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (91,'Asset Management',65);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (92,'Research and Development',35);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (93,'Customer Service',56);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (94,'Advertising',68);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (95,'Sales and Marketing',78);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (96,'Research and Development',72);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (97,'Quality Assurance',33);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (98,'Media Relations',40);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (99,'Sales and Marketing',76);
INSERT INTO "agente" (id_agente,ocupacion,reputacion_agente) VALUES (100,'Advertising',8);
