package modelo;
// Generated 08-abr-2016 1:26:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agente generated by hbm2java
 */
public class Agente  implements java.io.Serializable {


     private int idAgente;
     private Usuario usuario;
     private String ocupacion;
     private Double reputacionAgente;
     private Set servicios = new HashSet(0);

    public Agente() {
    }

	
    public Agente(Usuario usuario) {
        this.usuario = usuario;
    }
    public Agente(Usuario usuario, String ocupacion, Double reputacionAgente, Set servicios) {
       this.usuario = usuario;
       this.ocupacion = ocupacion;
       this.reputacionAgente = reputacionAgente;
       this.servicios = servicios;
    }
   
    public int getIdAgente() {
        return this.idAgente;
    }
    
    public void setIdAgente(int idAgente) {
        this.idAgente = idAgente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Double getReputacionAgente() {
        return this.reputacionAgente;
    }
    
    public void setReputacionAgente(Double reputacionAgente) {
        this.reputacionAgente = reputacionAgente;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


